### ISSUE TITLE
Specifying a filename with [hash]

### ISSUE THREAD

**Issue by callmemagnus** [oliviertassinari/serviceworker-webpack-plugin#50] opened 2018-01-25 07:35 UTC
My webpack plugin configuration for this plugin is the following:

```  
new ServiceWorkerWebpackPlugin({
      entry: path.join(__dirname, "src/scripts/sw.js"),
      filename: "sw.[hash:8].js"
    })
```

This generates everything "correctly" except that in the build I have the following error:

```
ERROR in ServiceWorkerPlugin: the `entry` option is incorrect.
```

This is the guilty part:

https://github.com/oliviertassinari/serviceworker-webpack-plugin/blob/560fdb7613746776ac934cca45579512dcd266f0/src/index.js#L130

I use a filename with a `[hash]` and the code expects the `compilation.assets` result object to contain the `sw.[hash:8].js` which obviously it won't because it will be something like `sw.3cdaa7e5.js`.

I understand the aim of testing if the resulting file is there but isn't there another way? Doesn't it fail somewhere else in the code?

**Comment by oliviertassinari** [comment] 2018-01-25 08:11
Oops, there is something wrong with our input warning logic. Your service worker file should have the same name between all deployments. The browser use the service worker filename to identifity it. Look in the repository history for more information. Basicaly, you will have an unbounded number of service worker installation.

**Comment by oliviertassinari** [comment] 2018-01-25 08:12
So, the plugin should throw when people are trying what you are doing. I thought the logic was already here.

**Comment by callmemagnus** [comment] 2018-01-25 08:21
:-) Ok I see. I thought browser would be more "intelligent" and allow only one registration per domain:port/pathname. I felt that the browser was not trying to fetch the newest version, so I wanted to give that solution a try.

**Comment by woutervanvliet** [comment] 2018-03-15 11:26
@callmemagnus Hope you managed to resolve the problem. If not, feel free to reach out and we'll see if we can help with your setup.

But as the plugin works as intended, I'm closing this issue.

**Closed** 2018-03-15 11:27 UTC
Labels: question

**Comment by kristenmills** [comment] 2018-05-03 16:41
So it would be useful in my case to be able to add a hash. We have a different from the normal setup but to kind of describe our use case:  We'd be reverse proxying `/service-worker.js` to an s3 bucket that contains the `service-worker.[hash].js`. This is because we have multiple instances of our application that are looking at this s3 bucket so we want to be able to distinguish between different versions of the service-worker. So it would be nice if we could have some way to specify a hash. I do understand the justification for not allowing it, but if i sent a PR that enabled you to use hash in the filename if you set another option like `dangerouslyAllowHash` or something like that., would that be reasonable?

**Comment by devCrossNet** [comment] 2018-05-03 17:31
Hey, have you tried something like this: 

```js
            new ServiceWorkerWebpackPlugin({
                                             entry: path.join(__dirname, '..', 'src/client/sw.ts') ,
                                             filename:`sw.${process.env.APP_HASH}.js`
            }),
```

then you can build you instance with the following command `APP_HASH=yourhash npm run build`.

I think this could be a solution to your use case. I tested it with a project right now and it works.

**Comment by kristenmills** [comment] 2018-05-03 18:36
Good thought, i can probably do something like that, thanks.
